spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: slingshot
    password: password
server:
  port: ${PORT:7070}    
    
management.endpoints.web.exposure.include: '*'    

logging.level.eu.xenit.contentgrid.webhooks.WebhookPublisher: DEBUG

contentgrid:
  webhooks:
    signing:
      jwt:
        #retired-keys: classpath:/keys/**.key, classpath:/keys/aprivate.key
        generate-key: true
        #signing-key:  classpath:/keys/private.key
        #issuer: https://something

    queue: contentgrid.slingshot
    requestTimeout: 30
    client:
    - endpoints:
         - uri: http://localhost:9001/fts/notify
           secret: abcd