spring:
  rabbitmq:
    host: localhost
    port: 5672
    
server:
  port: ${PORT:7070}    
    
management:
  endpoints:
    web:
      exposure:
        include: '*'


logging.level.eu.xenit.contentgrid.webhooks.WebhookPublisher: DEBUG

contentgrid:
  webhooks:
    signing:
      jwt:
        #retired-keys: classpath:/keys/**.key, classpath:/keys/aprivate.key
        generate-key: true
        #signing-key:  classpath:/keys/private.key
        #issuer: https://something

#    #queue: content-grid.events
#    #requestTimeout: 30 
#    client:            
#    - filter:
#        test: fake2
#        test2: abcd
#      endpoints:
#         - uri: http://localhost:9999/hooksite1
#           secret: abcd
#         - uri: http://localhost:9999/antivirus
#           secret: abcd         
#    - filter:
#        action: created
#        application: name1
#        type: account-state-zip
#        version: v1
#        test: fake
#      endpoints: 
#        - uri: http://localhost:8888/hooksite1
#          secret: abcd     
#    - filter:
#        action: created
#        application: name1
#        type: account-state-zip
#        version: v1
#        test: fake
#      endpoints: 
#        - uri: http://localhost:8080/hooksite3
#          secret: abcd     